### ISSUE TITLE
compiling in MacOS

### ISSUE THREAD

**Issue by o7o** [QVina/qvina#4]
how to compile it in Mac (OS: Yosemite)?

I got error:
```
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-ansi'
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [vina] Error 1
```
Thanks

This is my system
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
boost library version 1.64
```

**Comment by niko97320** [comment]
Dear all,

I'm facing the exact same problem. I've read during my searches on the web that it could be due to a problem regarding static libraries inclusion.

As I am far from an expert in compiling programs I couldn't fix it. Maybe this helps:
[https://github.com/rudolfolah/learning-jsoncpp/issues/2](https://github.com/rudolfolah/learning-jsoncpp/issues/2 )

Cheers

**Comment by aalhossary** [comment]
Hi all,
For macOS, simply remove the parameter '-static' from 2nd line.

This will be enough to make the tool compile (dynamic linking). The tool will work well, but well, but the executable will not be transferable to another machine.

This should be enough until I can figure out a final solution.

**Comment by henrytan2** [comment]
For those who still have this problem compiling I added this line to the Makefile and it worked:
`BOOST_LIB_VERSION=-mt`
